CREATE TABLE promotion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    annee VARCHAR(10)
);

CREATE TABLE etudiant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    promotion_id BIGINT NOT NULL,
    CONSTRAINT fk_etudiant_promotion FOREIGN KEY (promotion_id) REFERENCES promotion(id)
);

CREATE TABLE formateur (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL
);

CREATE TABLE session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre VARCHAR(200) NOT NULL,
    code VARCHAR(20) NOT NULL UNIQUE,
    ouverture_at TIMESTAMP NOT NULL,
    expiration_at TIMESTAMP NOT NULL,
    cloture_at TIMESTAMP,
    cloturee BOOLEAN NOT NULL DEFAULT FALSE,
    promotion_id BIGINT NOT NULL,
    formateur_id BIGINT,
    CONSTRAINT fk_session_promotion FOREIGN KEY (promotion_id) REFERENCES promotion(id),
    CONSTRAINT fk_session_formateur FOREIGN KEY (formateur_id) REFERENCES formateur(id)
);

CREATE TABLE presence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    etudiant_id BIGINT NOT NULL,
    marquee_at TIMESTAMP NOT NULL,
    source VARCHAR(20) NOT NULL,
    CONSTRAINT fk_presence_session FOREIGN KEY (session_id) REFERENCES session(id),
    CONSTRAINT fk_presence_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant(id),
    CONSTRAINT uq_presence UNIQUE (session_id, etudiant_id)
);

CREATE TABLE exercice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    etudiant_id BIGINT NOT NULL,
    lien VARCHAR(500) NOT NULL,
    depose_at TIMESTAMP NOT NULL,
    statut VARCHAR(30) NOT NULL,
    CONSTRAINT fk_exercice_session FOREIGN KEY (session_id) REFERENCES session(id),
    CONSTRAINT fk_exercice_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant(id),
    CONSTRAINT uq_exercice UNIQUE (session_id, etudiant_id)
);

CREATE TABLE relecture (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id BIGINT NOT NULL,
    relecteur_id BIGINT,
    note INTEGER,
    commentaire VARCHAR(2000),
    rendue_at TIMESTAMP,
    statut VARCHAR(20) NOT NULL,
    CONSTRAINT fk_relecture_exercice FOREIGN KEY (exercice_id) REFERENCES exercice(id),
    CONSTRAINT fk_relecture_relecteur FOREIGN KEY (relecteur_id) REFERENCES etudiant(id)
);

CREATE TABLE tentative_code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    etudiant_id BIGINT NOT NULL,
    nb_echecs INTEGER NOT NULL DEFAULT 0,
    bloque_jusqua TIMESTAMP,
    CONSTRAINT fk_tentative_session FOREIGN KEY (session_id) REFERENCES session(id),
    CONSTRAINT fk_tentative_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant(id),
    CONSTRAINT uq_tentative UNIQUE (session_id, etudiant_id)
);
