spring.datasource.url=jdbc:postgresql://db:5432/kfokam48
spring.datasource.username=kfokam48
spring.datasource.password=kfokam48
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.flyway.enabled=true
